class NoDocsCollectedException(Exception):
    pass

class CanceledTaskException(Exception):
    pass
